<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
            <div class="flex items-center gap-2">
                <span class="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-100 text-indigo-600 dark:bg-indigo-900/40 dark:text-indigo-300">⌁</span>
                <h1 class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">Statistik Kependudukan</h1>
            </div>
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Ringkasan demografi dan komposisi penduduk.</p>
        </div>
        @if(auth()->user()->isSuperAdmin())
            <select wire:model.live="selectedTenantId" class="rounded-xl border-gray-300 bg-white px-4 py-2.5 text-sm font-medium shadow-sm dark:border-gray-700 dark:bg-gray-800 dark:text-white"><option value="">Pilih tenant</option>@foreach(\App\Models\Tenant::query()->orderBy('name')->get() as $tenant)<option value="{{ $tenant->id }}">{{ $tenant->name }}</option>@endforeach</select>
        @endif
    </div>

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div class="group relative overflow-hidden rounded-2xl border border-blue-100 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg dark:border-blue-900/50 dark:bg-gray-800">
            <div class="absolute right-0 top-0 h-24 w-24 rounded-full bg-blue-500/10 blur-2xl"></div><div class="relative flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">Total Penduduk</p><p class="mt-2 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">{{ number_format($totalCitizens) }}</p><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Warga terdata</p></div><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-900/40 dark:text-blue-300">👥</span></div>
        </div>
        <div class="group relative overflow-hidden rounded-2xl border border-violet-100 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg dark:border-violet-900/50 dark:bg-gray-800">
            <div class="absolute right-0 top-0 h-24 w-24 rounded-full bg-violet-500/10 blur-2xl"></div><div class="relative flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">Total KK</p><p class="mt-2 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">{{ number_format($totalFamilies) }}</p><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Kartu keluarga</p></div><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-50 text-violet-600 dark:bg-violet-900/40 dark:text-violet-300">⌂</span></div>
        </div>
        <div class="group relative overflow-hidden rounded-2xl border border-sky-100 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg dark:border-sky-900/50 dark:bg-gray-800">
            <div class="absolute right-0 top-0 h-24 w-24 rounded-full bg-sky-500/10 blur-2xl"></div><div class="relative flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">Laki-laki</p><p class="mt-2 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">{{ number_format($male) }}</p><p class="mt-1 text-xs text-sky-600 dark:text-sky-400">{{ $totalCitizens ? number_format(($male / $totalCitizens) * 100, 1) : 0 }}% dari penduduk</p></div><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-50 text-sky-600 dark:bg-sky-900/40 dark:text-sky-300">♂</span></div>
        </div>
        <div class="group relative overflow-hidden rounded-2xl border border-pink-100 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg dark:border-pink-900/50 dark:bg-gray-800">
            <div class="absolute right-0 top-0 h-24 w-24 rounded-full bg-pink-500/10 blur-2xl"></div><div class="relative flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">Perempuan</p><p class="mt-2 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">{{ number_format($female) }}</p><p class="mt-1 text-xs text-pink-600 dark:text-pink-400">{{ $totalCitizens ? number_format(($female / $totalCitizens) * 100, 1) : 0 }}% dari penduduk</p></div><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-pink-50 text-pink-600 dark:bg-pink-900/40 dark:text-pink-300">♀</span></div>
        </div>
    </div>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-gray-800">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div class="flex items-center gap-2"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-900/40 dark:text-indigo-300">▥</span><div><h2 class="font-semibold text-gray-900 dark:text-white">Piramida Penduduk</h2><p class="mt-0.5 text-xs text-gray-500 dark:text-gray-400">Distribusi penduduk menurut kelompok umur 5 tahunan dan jenis kelamin.</p></div></div></div><div class="flex gap-5 text-xs font-medium text-gray-600 dark:text-gray-300"><span class="flex items-center gap-1.5"><span class="h-2.5 w-2.5 rounded-full bg-sky-500"></span>Laki-laki</span><span class="flex items-center gap-1.5"><span class="h-2.5 w-2.5 rounded-full bg-pink-500"></span>Perempuan</span></div></div>
        <div class="mt-6 overflow-x-auto"><div class="mx-auto min-w-[620px] max-w-5xl"><div class="mb-3 grid grid-cols-[1fr_64px_1fr] items-center gap-2 text-xs font-semibold uppercase tracking-wide"><div class="text-right text-sky-600 dark:text-sky-400">Laki-laki <span class="font-normal normal-case text-gray-500">({{ number_format($male) }})</span></div><div></div><div class="text-pink-600 dark:text-pink-400">Perempuan <span class="font-normal normal-case text-gray-500">({{ number_format($female) }})</span></div></div><div class="space-y-1">@foreach($ageGroups as $label => $group)<div class="grid grid-cols-[1fr_64px_1fr] items-center gap-2"><div class="flex items-center justify-end gap-2"><span class="w-12 text-right text-[11px] font-semibold tabular-nums text-slate-500 dark:text-slate-400">{{ number_format($group['male']) }}</span><div class="h-6 flex-1 overflow-hidden rounded-l-md bg-slate-100 dark:bg-slate-900"><div class="ml-auto h-full rounded-l-md bg-gradient-to-l from-sky-400 to-blue-600 transition-all duration-300" style="width: {{ $group['male_width'] }}%"></div></div></div><div class="rounded-md border border-slate-200 bg-slate-50 py-1 text-center text-[11px] font-bold text-slate-600 dark:border-slate-700 dark:bg-slate-700 dark:text-slate-200">{{ $label }}</div><div class="flex items-center gap-2"><div class="h-6 flex-1 overflow-hidden rounded-r-md bg-slate-100 dark:bg-slate-900"><div class="h-full rounded-r-md bg-gradient-to-r from-pink-400 to-rose-500 transition-all duration-300" style="width: {{ $group['female_width'] }}%"></div></div><span class="w-12 text-left text-[11px] font-semibold tabular-nums text-slate-500 dark:text-slate-400">{{ number_format($group['female']) }}</span></div></div>@endforeach</div><div class="mt-4 grid grid-cols-[1fr_64px_1fr] gap-2 text-[10px] text-slate-400 dark:text-slate-500"><div class="flex justify-between px-12"><span>0</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div><div></div><div class="flex justify-between px-12"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0</span></div></div></div></div>
        @php $classifiedAge = $ageGroups->sum('total'); $unclassifiedAge = max(0, $totalCitizens - $classifiedAge); @endphp
        @if($unclassifiedAge > 0)<div class="mt-4 flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700 dark:border-amber-900/50 dark:bg-amber-900/20 dark:text-amber-300"><span class="font-bold">{{ number_format($unclassifiedAge) }}</span> penduduk belum masuk piramida karena tanggal lahir belum tersedia.</div>@endif
    </section>

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <section class="group relative overflow-hidden rounded-2xl border border-amber-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-amber-900/60 dark:bg-gray-800"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-amber-600 dark:text-amber-400">Balita</p><p class="mt-2 text-3xl font-extrabold text-gray-900 dark:text-white">{{ number_format($toddlers) }}</p><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Usia 0–5 tahun</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-100 text-amber-600 dark:bg-amber-900/40 dark:text-amber-300">●</span></div></section>
        <section class="group relative overflow-hidden rounded-2xl border border-emerald-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-emerald-900/60 dark:bg-gray-800"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">Anak</p><p class="mt-2 text-3xl font-extrabold text-gray-900 dark:text-white">{{ number_format($children) }}</p><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Usia 6–14 tahun</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-600 dark:bg-emerald-900/40 dark:text-emerald-300">●</span></div></section>
        <section class="group relative overflow-hidden rounded-2xl border border-indigo-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-indigo-900/60 dark:bg-gray-800"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">Usia Produktif</p><p class="mt-2 text-3xl font-extrabold text-gray-900 dark:text-white">{{ number_format($productiveAge) }}</p><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Usia 15–64 tahun</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-100 text-indigo-600 dark:bg-indigo-900/40 dark:text-indigo-300">●</span></div></section>
        <section class="group relative overflow-hidden rounded-2xl border border-purple-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-purple-900/60 dark:bg-gray-800"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-purple-600 dark:text-purple-400">Lansia</p><p class="mt-2 text-3xl font-extrabold text-gray-900 dark:text-white">{{ number_format($elderly) }}</p><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Usia 65+ tahun</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-purple-100 text-purple-600 dark:bg-purple-900/40 dark:text-purple-300">●</span></div></section>
    </div>

    <div class="grid gap-6 lg:grid-cols-2">
        <section class="rounded-2xl border border-orange-200 bg-white p-5 shadow-sm dark:border-orange-900/60 dark:bg-gray-800"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400">▤</div><div><h2 class="font-semibold text-gray-900 dark:text-white">Statistik Pekerjaan</h2><p class="text-xs text-gray-500 dark:text-gray-400">Pekerjaan warga berdasarkan jumlah terbanyak</p></div></div><div class="mt-5 space-y-3">@forelse($occupations as $label => $total)<div class="rounded-lg border border-orange-100 bg-orange-50/70 p-3 dark:border-orange-900/40 dark:bg-orange-900/20"><div class="mb-2 flex items-center justify-between gap-3"><span class="min-w-0 truncate text-sm font-medium text-gray-700 dark:text-gray-200">{{ $label ?: 'Tidak diisi' }}</span><span class="shrink-0 rounded-full bg-orange-500 px-2.5 py-1 text-xs font-bold text-white">{{ number_format($total) }}</span></div><div class="h-2 overflow-hidden rounded-full bg-orange-100 dark:bg-orange-950/50"><div class="h-full rounded-full bg-gradient-to-r from-amber-400 to-orange-500" style="width: {{ round(($total / max(1, (int) $occupations->max())) * 100, 2) }}%"></div></div></div>@empty<div class="rounded-lg border border-dashed border-orange-200 p-4 text-sm text-gray-500 dark:border-orange-900 dark:text-gray-400">Belum ada data pekerjaan.</div>@endforelse</div></section>

        <section class="rounded-2xl border border-rose-200 bg-white p-5 shadow-sm dark:border-rose-900/60 dark:bg-gray-800"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-rose-100 text-rose-600 dark:bg-rose-900/30 dark:text-rose-400">♥</div><div><h2 class="font-semibold text-gray-900 dark:text-white">Status Perkawinan</h2><p class="text-xs text-gray-500 dark:text-gray-400">Distribusi status perkawinan warga</p></div></div><div class="mt-5 space-y-3">@forelse($marital as $label => $total)<div class="flex items-center justify-between rounded-lg border border-rose-100 bg-rose-50/70 px-3 py-3 shadow-sm dark:border-rose-900/40 dark:bg-rose-900/20"><span class="text-sm font-medium capitalize text-gray-700 dark:text-gray-200">{{ $label ?: 'Tidak diisi' }}</span><span class="rounded-full bg-rose-500 px-3 py-1 text-xs font-bold text-white shadow-sm">{{ number_format($total) }}</span></div>@empty<div class="rounded-lg border border-dashed border-rose-200 p-4 text-sm text-gray-500 dark:border-rose-900 dark:text-gray-400">Belum ada data perkawinan.</div>@endforelse</div></section>
    </div>
</div>
