<?php

declare(strict_types=1);

use App\Models\Citizen;
use Illuminate\Support\Facades\Validator;
use Livewire\Attributes\Layout;
use Livewire\Volt\Component;
use Livewire\WithPagination;

new #[Layout('layouts.app')] class extends Component {
    use WithPagination;
    public int $perPage = 10;
    public string $search = '';
    public bool $showForm = false;
    public ?string $editingId = null;
    public string $nik = '', $nama_lengkap = '', $tempat_lahir = '', $tanggal_lahir = '', $jenis_kelamin = '', $golongan_darah = '', $agama = '', $status_perkawinan = '', $pendidikan = '', $pekerjaan = '', $kewarganegaraan = 'WNI', $status_kependudukan = 'active';

    public function mount(): void { abort_unless(auth()->user()?->tenant_id && auth()->user()->hasPermission('population.view'), 403); }
    public function updatedSearch(): void { $this->resetPage(); }
    public function create(): void { abort_unless(auth()->user()->hasPermission('population.manage'), 403); $this->resetForm(); $this->showForm = true; }
    private function query() { return Citizen::query()->where('tenant_id', auth()->user()->tenant_id)->when($this->search !== '', fn($q) => $q->where(fn($q) => $q->where('nik','ilike','%'.$this->search.'%')->orWhere('nama_lengkap','ilike','%'.$this->search.'%')))->orderBy('nama_lengkap'); }
    public function edit(string $id): void { abort_unless(auth()->user()->hasPermission('population.manage'), 403); $c=$this->query()->findOrFail($id); $this->editingId=$c->id; foreach(['nik','nama_lengkap','tempat_lahir','jenis_kelamin','golongan_darah','agama','status_perkawinan','pendidikan','pekerjaan','kewarganegaraan','status_kependudukan'] as $f) $this->{$f}=(string)($c->{$f}??''); $this->tanggal_lahir=$c->tanggal_lahir?->format('Y-m-d')??''; $this->showForm=true; }
    public function save(): void { abort_unless(auth()->user()->hasPermission('population.manage'),403); $data=Validator::make($this->only(['nik','nama_lengkap','tempat_lahir','tanggal_lahir','jenis_kelamin','golongan_darah','agama','status_perkawinan','pendidikan','pekerjaan','kewarganegaraan','status_kependudukan']),['nik'=>['required','digits:16','unique:citizens,nik,'.($this->editingId??'NULL').',id,tenant_id,'.auth()->user()->tenant_id],'nama_lengkap'=>['required','string','max:255'],'tempat_lahir'=>['nullable','string','max:255'],'tanggal_lahir'=>['nullable','date'],'jenis_kelamin'=>['nullable','in:male,female'],'golongan_darah'=>['nullable','in:A,B,AB,O,unknown'],'agama'=>['nullable','string','max:40'],'status_perkawinan'=>['nullable','string','max:30'],'pendidikan'=>['nullable','string','max:100'],'pekerjaan'=>['nullable','string','max:150'],'kewarganegaraan'=>['required','string','max:50'],'status_kependudukan'=>['required','string','max:30']])->validate(); $data['tenant_id']=auth()->user()->tenant_id; $data['updated_by']=auth()->id(); if($this->editingId){$this->query()->findOrFail($this->editingId)->update($data);}else{$data['created_by']=auth()->id();Citizen::create($data);} $this->resetForm(); $this->dispatch('toast',type:'success',message:'Data warga berhasil disimpan.'); }
    public function resetForm(): void { foreach(['nik','nama_lengkap','tempat_lahir','tanggal_lahir','jenis_kelamin','golongan_darah','agama','status_perkawinan','pendidikan','pekerjaan'] as $f) $this->{$f}=''; $this->kewarganegaraan='WNI'; $this->status_kependudukan='active'; $this->editingId=null; $this->showForm=false; $this->resetValidation(); }
    public function with(): array { return ['citizens'=>$this->query()->paginate($this->perPage)]; }
};
?>
<div class="space-y-6">
<div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm text-slate-500">Kependudukan</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-slate-900">Data Warga</h1><p class="mt-1 text-sm text-slate-500">Master data penduduk.</p></div>@if(auth()->user()->hasPermission('population.manage'))<button wire:click="create" class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">+ Tambah Warga</button>@endif</div>
<div class="flex gap-3"><input wire:model.live.debounce.300ms="search" placeholder="Cari NIK atau nama..." class="w-full max-w-md rounded-xl border border-slate-200 px-4 py-2.5 text-sm"></div>
@if($showForm)<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">{{ $editingId?'Edit Data Warga':'Tambah Data Warga' }}</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
@foreach([['nik','NIK'],['nama_lengkap','Nama Lengkap'],['tempat_lahir','Tempat Lahir'],['tanggal_lahir','Tanggal Lahir'],['pendidikan','Pendidikan'],['pekerjaan','Pekerjaan'],['agama','Agama'],['status_perkawinan','Status Perkawinan']] as [$f,$l])<div><label class="text-sm font-medium text-slate-700">{{ $l }}</label><input wire:model="{{ $f }}" type="{{ $f==='tanggal_lahir'?'date':'text' }}" class="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">@error($f)<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>@endforeach
<div><label class="text-sm font-medium">Jenis Kelamin</label><select wire:model="jenis_kelamin" class="mt-2 w-full rounded-xl border px-3 py-2.5"><option value="">Pilih</option><option value="male">Laki-laki</option><option value="female">Perempuan</option></select></div><div><label class="text-sm font-medium">Golongan Darah</label><select wire:model="golongan_darah" class="mt-2 w-full rounded-xl border px-3 py-2.5"><option value="">Pilih</option>@foreach(['A','B','AB','O','unknown'] as $v)<option value="{{$v}}">{{$v}}</option>@endforeach</select></div><div><label class="text-sm font-medium">Kewarganegaraan</label><input wire:model="kewarganegaraan" class="mt-2 w-full rounded-xl border px-3 py-2.5"></div><div><label class="text-sm font-medium">Status Kependudukan</label><select wire:model="status_kependudukan" class="mt-2 w-full rounded-xl border px-3 py-2.5"><option value="active">Aktif</option><option value="inactive">Tidak Aktif</option><option value="deceased">Meninggal</option><option value="moved">Pindah</option></select></div></div><div class="mt-5 flex justify-end gap-3"><button wire:click="resetForm" class="rounded-xl border px-4 py-2.5">Batal</button><button wire:click="save" class="rounded-xl bg-slate-900 px-5 py-2.5 font-semibold text-white">Simpan</button></div></div>@endif
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr><th class="px-6 py-3 text-left text-xs uppercase text-slate-500">Nama</th><th class="px-6 py-3 text-left text-xs uppercase text-slate-500">NIK</th><th class="hidden px-6 py-3 text-left text-xs uppercase text-slate-500 md:table-cell">TTL</th><th class="px-6 py-3 text-left text-xs uppercase text-slate-500">Status</th><th class="px-6 py-3 text-right text-xs uppercase text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($citizens as $c)<tr><td class="px-6 py-4 font-medium">{{$c->nama_lengkap}}</td><td class="px-6 py-4 text-sm">{{$c->nik}}</td><td class="hidden px-6 py-4 text-sm md:table-cell">{{$c->tempat_lahir?:'-'}}, {{$c->tanggal_lahir?->format('d/m/Y')?:'-'}}</td><td class="px-6 py-4 text-sm">{{ucfirst($c->status_kependudukan)}}</td><td class="px-6 py-4 text-right">@if(auth()->user()->hasPermission('population.manage'))<button wire:click="edit('{{$c->id}}')" class="text-sm font-semibold">Edit</button>@endif</td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-sm text-slate-500">Belum ada data warga.</td></tr>@endforelse</tbody></table></div><div class="border-t px-6 py-3">{{$citizens->links()}}</div></div>
</div>
